name: Sync wiki

on:
  push:
    branches:
      - main
    paths:
      - docs/wiki.md
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - name: Sync wiki content
        run: |
          cp docs/wiki.md wiki/Home.md
      - name: Commit and push changes
        run: |
          cd wiki
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add Home.md
            git commit -m "Sync wiki from docs/wiki.md"
            git push
          fi
